baseURL: "https://main--sfcsports.netlify.app/"
languageCode: "en-us"
title: "SFC Sports"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  github: "https://github.com/Smyan-Narang"
  instagram: "https://www.instagram.com/smyan.narang0505/"
  dribbble: "#"
taxonomies:
  author: authors
